import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import {
  Drawer,
  List,
  ListItemButton,
  ListItemIcon,
  ListItem,
  ListItemText,
} from "@mui/material";
import InboxIcon from "@mui/icons-material/MoveToInbox";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Drawer
          sx={{
            width: 300,
            flexShrink: 0,
            "& .MuiDrawer-paper": {
              width: 300,
              boxSizing: "border-box",
            },
          }}
          variant="permanent"
          anchor="left"
        >
          <List>
            <List component="div" disablePadding>
              <ListItemButton>
                <ListItemText primary="Storage" />
              </ListItemButton>
            </List>
            <List component="div" disablePadding>
              <ListItemButton sx={{ pl: 4 }}>
                <ListItemIcon>
                  <InboxIcon />
                </ListItemIcon>
                <ListItemText primary="AWS S3" />
              </ListItemButton>
            </List>

            <List component="div" disablePadding>
              <ListItemButton>
                <ListItemText primary="AI Models" />
              </ListItemButton>
            </List>
            <ListItemButton sx={{ pl: 4 }}>
              <ListItemIcon>
                <InboxIcon />
              </ListItemIcon>
              <ListItemText primary="Whisper" />
            </ListItemButton>
          </List>
        </Drawer>
      </main>
    </>
  );
}
